"""
Enumerate any Qualcomm CodeLinaro Artifactory repository via the public
JFrog REST API.

CodeLinaro hosts Qualcomm's Adreno-tuned MLC-LLM distribution at::

    https://codelinaro.jfrog.io/ui/native/clo-472-adreno-opensource-ai/

The web UI is a JS-heavy SPA and `web_fetch` cannot scrape it, but the
underlying JFrog REST API is open and returns JSON. This script walks
the storage tree and dumps every file's metadata.

Usage::

    python jfrog_clo_catalog.py ^
        --repo clo-472-adreno-opensource-ai ^
        --path mlc-llm ^
        --out-json codelinaro_catalog.json ^
        --out-md   codelinaro_catalog.md
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

DEFAULT_BASE = "https://codelinaro.jfrog.io/artifactory"
USER_AGENT = "tether-research/1.0 (+https://github.com/Lando-00/Tether)"


@dataclass
class Node:
    path: str
    is_folder: bool
    size: int = 0
    sha1: Optional[str] = None
    sha256: Optional[str] = None
    md5: Optional[str] = None
    created: Optional[str] = None
    last_modified: Optional[str] = None
    download_uri: Optional[str] = None


def _http_get_json(url: str) -> Any:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def storage_url(base: str, repo: str, path: str = "") -> str:
    p = path.strip("/")
    suffix = f"/{p}" if p else ""
    return f"{base}/api/storage/{repo}{suffix}"


def walk(base: str, repo: str, path: str) -> list[Node]:
    out: list[Node] = []
    info = _http_get_json(storage_url(base, repo, path))
    if "children" in info:
        out.append(Node(path=path or "/", is_folder=True,
                        created=info.get("created"),
                        last_modified=info.get("lastModified")))
        for child in info["children"]:
            child_path = (path.rstrip("/") + child["uri"]) if path else child["uri"].lstrip("/")
            if child.get("folder"):
                out.extend(walk(base, repo, child_path))
            else:
                file_info = _http_get_json(storage_url(base, repo, child_path))
                checksums = file_info.get("checksums") or {}
                out.append(Node(
                    path=child_path,
                    is_folder=False,
                    size=int(file_info.get("size") or 0),
                    sha1=checksums.get("sha1"),
                    sha256=checksums.get("sha256"),
                    md5=checksums.get("md5"),
                    created=file_info.get("created"),
                    last_modified=file_info.get("lastModified"),
                    download_uri=file_info.get("downloadUri"),
                ))
    else:
        checksums = info.get("checksums") or {}
        out.append(Node(
            path=path or "/",
            is_folder=False,
            size=int(info.get("size") or 0),
            sha1=checksums.get("sha1"),
            sha256=checksums.get("sha256"),
            md5=checksums.get("md5"),
            created=info.get("created"),
            last_modified=info.get("lastModified"),
            download_uri=info.get("downloadUri"),
        ))
    return out


def render_md(nodes: list[Node], base: str, repo: str, path: str) -> str:
    lines: list[str] = []
    lines.append(f"# CodeLinaro `{repo}` — `{path}` catalog")
    lines.append("")
    lines.append(
        f"_Auto-generated by `scripts/research/jfrog_clo_catalog.py`. "
        f"Source: <{base}/api/storage/{repo}/{path}>._"
    )
    lines.append("")
    files = [n for n in nodes if not n.is_folder]
    folders = [n for n in nodes if n.is_folder]
    lines.append(f"Folders walked: **{len(folders)}** · Files: **{len(files)}** · "
                 f"Total bytes: **{sum(n.size for n in files):,}** "
                 f"({sum(n.size for n in files) / (1024 ** 3):.2f} GB).")
    lines.append("")
    lines.append("## Files")
    lines.append("")
    lines.append("| Path | Size | Last modified | SHA-256 |")
    lines.append("|------|-----:|---------------|---------|")
    for n in sorted(files, key=lambda x: x.path):
        size_mb = n.size / (1024 ** 2)
        size_cell = f"{size_mb:,.1f} MB" if size_mb >= 0.1 else f"{n.size} B"
        last_mod = (n.last_modified or "")[:10]
        sha = (n.sha256 or "")[:12]
        lines.append(f"| `{n.path}` | {size_cell} | {last_mod} | `{sha}…` |")
    lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("--base", default=DEFAULT_BASE)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--path", default="")
    parser.add_argument("--out-json", type=Path, default=None)
    parser.add_argument("--out-md", type=Path, default=None)
    args = parser.parse_args(argv)

    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    except Exception:
        pass

    try:
        nodes = walk(args.base, args.repo, args.path)
    except (urllib.error.HTTPError, urllib.error.URLError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.out_json:
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(
            json.dumps([dataclasses.asdict(n) for n in nodes], indent=2),
            encoding="utf-8",
        )
        print(f"wrote {args.out_json}")

    md = render_md(nodes, args.base, args.repo, args.path)
    if args.out_md:
        args.out_md.parent.mkdir(parents=True, exist_ok=True)
        args.out_md.write_text(md, encoding="utf-8")
        print(f"wrote {args.out_md}")
    elif not args.out_json:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
